### ISSUE TITLE
Document (and/or improve) situations that cause silent failure of decoding

### ISSUE THREAD

**Issue by TomiS** [reasonml-labs/decco#40]
I've noticed there can quite easily be situations where a codec is syntactically and type-wise valid but fails silently in runtime producing a completely empty result.

While I think producing a completely empty result is probably better than just ignoring single fields, and it's likely impossible to be able to catch all of the errors on type level in compile time, it would be very nice to have more specific documentation on what causes these situations.

I'm also thinking a runtime error would about the exact location of failure would be super useful. Atm. I'm returning `Decco.error("foo")` in some situations but I'm not sure if they do anything.

**Comment by ryb73** [comment]
Hi, could you provide a specific example of the issue you're encountering?

**Comment by TomiS** [comment]
@ryb73 At least one situation that happened to me just today was that I was trying to decode an API payload which I thought would contain integers. They ended up being floats and receiving floats caused https://github.com/reasonml-labs/decco/blob/master/src/Decco.re#L27-L36 to fail.

I'm wondering, should the Belt.Result.Error or Decco.error somehow appear somewhere? Because to me they don't seem to do anything.

**Comment by ryb73** [comment]
I recommend reading about OCaml/Reason's Result type. Here's a brief description of it: https://ocaml.org/learn/tutorials/error_handling.html#Result-type

The short answer is that decco's `_decode` functions return a result that's either the decoded value or an error. If it's an error, it's up to you to handle it however you want.

**Comment by TomiS** [comment]
@ryb73 Hmm, indeed it might be more about me not properly handling the error than anything else. I just seem to dispatch a reductive action on error that does nothing. I could easily log errors there myself. Thanks for the pointer. I'll close this ticket.
