### ISSUE TITLE
Support new [@unboxed] attribute for transparent runtime representations.

### ISSUE THREAD

**Issue by erlandsona** [reasonml-labs/decco#49]
Currently if I write the equivalent of a "newtype" from Haskell which is enabled by the new [@unboxed] attribute since 7.0.2-dev.1 I get this runtime error message "Not a variant". 
Which makes sense but it'd be nice to support this...

**Comment by austindd** [comment]
I second this request. The `@unboxed` attribute is invaluable for being able to serialize GADT types without boxing them and incurring overhead.

**Comment by erlandsona** [comment]
@austindd hey mate! Yeh I ended up just building out a module functor to serve my use case but it's like 10x more code just to be able to decco some simple primitive types like int and string with a wrapping data type.

**Comment by ryb73** [comment]
Fixed. Thanks for the request!
